name: Android APK Release

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build web
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Sync Capacitor
        working-directory: ./frontend
        run: npx cap sync android

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure gradlew + accept SDK
        working-directory: ./frontend/android
        run: |
          chmod +x gradlew
          yes | ./gradlew --no-daemon --console=plain tasks || true

      - name: Decode keystore
        working-directory: ./frontend/android/app
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > alsadika.keystore
          ls -lh alsadika.keystore

      - name: keystore.properties
        working-directory: ./frontend/android/app
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cat > keystore.properties <<EOF
          storeFile=alsadika.keystore
          storePassword=${ANDROID_KEYSTORE_PASSWORD}
          keyAlias=${ANDROID_KEY_ALIAS}
          keyPassword=${ANDROID_KEY_PASSWORD}
          EOF
          cat keystore.properties

      - name: Build Release
        working-directory: ./frontend/android
        run: ./gradlew --no-daemon --console=plain assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: al-sadika-release
          path: frontend/android/app/build/outputs/apk/release/*.apk
